// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLwhTGGDJVJ4DGcNyvXvF2t2L82mmXKJo',
    appId: '1:697408930482:web:c9daaecec57ad35306ffab',
    messagingSenderId: '697408930482',
    projectId: 'studyapp-40cec',
    authDomain: 'studyapp-40cec.firebaseapp.com',
    storageBucket: 'studyapp-40cec.appspot.com',
    measurementId: 'G-TJMKCZFG0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1lPooQObEhVrbhIZoKc8UucvWLKPHYdw',
    appId: '1:697408930482:android:316554635c2552df06ffab',
    messagingSenderId: '697408930482',
    projectId: 'studyapp-40cec',
    storageBucket: 'studyapp-40cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8y-L5pz5csaokM9zZ5dVq1_mVgx5hv8',
    appId: '1:697408930482:ios:a691de97b9be98c006ffab',
    messagingSenderId: '697408930482',
    projectId: 'studyapp-40cec',
    storageBucket: 'studyapp-40cec.appspot.com',
    iosClientId: '697408930482-ut5164lse4mjfu167puf2d7l0lpqo8qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8y-L5pz5csaokM9zZ5dVq1_mVgx5hv8',
    appId: '1:697408930482:ios:a81036a3ca3d0ca006ffab',
    messagingSenderId: '697408930482',
    projectId: 'studyapp-40cec',
    storageBucket: 'studyapp-40cec.appspot.com',
    iosClientId: '697408930482-dmecgkht8o5n5jstq1hkjt6vdspg1b3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp.RunnerTests',
  );
}
